# This file was generated by GoReleaser. DO NOT EDIT.
class KubeTrivy < Formula
  desc ""
  homepage "https://github.com/masahiro331/kube-trivy"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/masahiro331/kube-trivy/releases/download/v0.1.0/kube-trivy_0.1.0_macOS-64bit.tar.gz"
    sha256 "fe3367c7b00e630d3d3c5ed01c08979e6650c9d31ab620cdf5a2fa8035e3bd80"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/masahiro331/kube-trivy/releases/download/v0.1.0/kube-trivy_0.1.0_Linux-64bit.tar.gz"
      sha256 "638fb44c0a4e53e53397bb269007b0b4b25cbc579cc71f9d014404f8e79605b6"
    end
  end
  
  depends_on "rpm"

  def install
    bin.install "kubetrivy"
  end

  test do
    system "#{bin}/program --version"
  end
end
